name: Publish nightly snapshot
on:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  publish-image:
    name: Publish nightly snapshot
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Release Container Runtime
        run: |
          echo "SHORTER_SHA=$(${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV
          echo $SHORTER_SHA
          echo "SHORTER_SHA=$(echo $(${{ github.sha }} | cut -c1-8))" >> $GITHUB_ENV
          echo $SHORTER_SHA
          echo "SHORTER_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo $SHORTER_SHA
          make container-runtime-build
          make container-runtime-snapshot-push TAG=$SHORTER_SHA
